apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yaml -o stream-beaver-helm
    kompose.service.type: LoadBalancer
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mqtt-broker
  name: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mqtt-broker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yaml -o stream-beaver-helm
        kompose.service.type: LoadBalancer
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mqtt-broker
    spec:
      containers:
        - image: eclipse-mosquitto:latest
          name: mqtt-broker
          ports:
            - containerPort: 1883
              protocol: TCP
          volumeMounts:
            - mountPath: /mosquitto/config
              name: mqtt-broker-cm0
            - mountPath: /mosquitto/data
              name: mosquitto-data
            - mountPath: /mosquitto/log
              name: mosquitto-log
      hostname: mqtt-broker
      restartPolicy: Always
      volumes:
        - configMap:
            name: mqtt-broker-cm0
          name: mqtt-broker-cm0
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: mosquitto-data
        - name: mosquitto-log
          persistentVolumeClaim:
            claimName: mosquitto-log
