apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yaml -o stream-beaver-helm
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mqtt-to-mongodb
  name: mqtt-to-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mqtt-to-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yaml -o stream-beaver-helm
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mqtt-to-mongodb
    spec:
      containers:
        - args:
            - sh
            - -c
            - npm install && node mqtt-to-mongodb.js
          image: node:22-slim
          name: mqtt-to-mongodb
          volumeMounts:
            - mountPath: /app/mqtt-to-mongodb.js
              name: mqtt-to-mongodb-cm0
              subPath: mqtt-to-mongodb.js
            - mountPath: /app/auto-indexer.js
              name: mqtt-to-mongodb-cm1
              subPath: auto-indexer.js
            - mountPath: /app/util.js
              name: mqtt-to-mongodb-cm2
              subPath: util.js
            - mountPath: /app/package.json
              name: mqtt-to-mongodb-cm3
              subPath: package.json
            - mountPath: /app/config.json
              name: mqtt-to-mongodb-cm4
              subPath: config.json
          workingDir: /app
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: mqtt-to-mongodb.js
                path: mqtt-to-mongodb.js
            name: mqtt-to-mongodb-cm0
          name: mqtt-to-mongodb-cm0
        - configMap:
            items:
              - key: auto-indexer.js
                path: auto-indexer.js
            name: mqtt-to-mongodb-cm1
          name: mqtt-to-mongodb-cm1
        - configMap:
            items:
              - key: util.js
                path: util.js
            name: mqtt-to-mongodb-cm2
          name: mqtt-to-mongodb-cm2
        - configMap:
            items:
              - key: package.json
                path: package.json
            name: mqtt-to-mongodb-cm3
          name: mqtt-to-mongodb-cm3
        - configMap:
            items:
              - key: config.json
                path: config.json
            name: mqtt-to-mongodb-cm4
          name: mqtt-to-mongodb-cm4
